### ISSUE TITLE
Release code and models?

### ISSUE THREAD

**Issue by oxFFFF-Q** [Liang-ZX/AdaptDiffuser#1]
Hi, are there any plans to release the code and models?
Thanks!

**Comment by Liang-ZX** [comment]
> Hi, are there any plans to release the code and models? Thanks!

Hi, we will try to release our code before the end of July (before the presentation in ICML). Thank you.

**Comment by alexpostnikov** [comment]
Hello!
Is there any update on the release date of the code?

**Comment by skylzh14** [comment]
Hello！I can not see the code,when will you release the code and models?
Thanks!

**Comment by choucaicai** [comment]
Hello!
Is there any update on the release date of the code?
Thanks!

**Comment by Liang-ZX** [comment]
> Hello! Is there any update on the release date of the code? Thanks!

Yes, I'm sorry for the latency. Please check it at Sep. 23rd. Thank you.

**Comment by Liang-ZX** [comment]
> Hello! Is there any update on the release date of the code?

Hello, I'm sorry for the latency. Please check it at Sep. 23rd. Thank you.

**Comment by gunshi** [comment]
Hey! Wanted to check if the code and models (esp. for meta world experiments) were released yet? Because the above comment says Sept 23rd, maybe it's a typo?
Thanks!

**Comment by Liang-ZX** [comment]
> Hey! Wanted to check if the code and models (esp. for meta world experiments) were released yet? Because the above comment says Sept 23rd, maybe it's a typo? Thanks!

All codes for kuka have been released. And we do not have meta world experiments for AdaptDiffuser. Maybe you mean MetaDiffuser? I suggest you send an email to Dr. Fei Ni. Thank you.
