### ISSUE TITLE
question about reward guidance in Mujoco tasks

### ISSUE THREAD

**Issue by yuxudong20** [Liang-ZX/AdaptDiffuser#3]
Hello, i cannot understand the reward guidance synthetic generation for continuous reward function. Could you give more information or related codes?
![image](https://github.com/Liang-ZX/adaptdiffuser/assets/47274016/32f7281b-7232-4b14-9e5e-a9774ac064ff)

**Comment by Liang-ZX** [comment]
Our implementation is similar to this [file](https://github.com/jannerm/diffuser/blob/main/diffuser/sampling/functions.py) of Diffuser. And we will release our code of Mujoco later.

**Comment by yuxudong20** [comment]
Thanks. After reading the implementation of Diffuser, i have known the generation process and how $\mu+\Sigma*g$ works. But i still have a question about the binary random variable indicating the optimality. What does this mean and how it influence the generation process?

**Comment by Liang-ZX** [comment]
It's a misunderstanding. We just means using a random variable obeying Bernoulli distribution.

<img width="357" alt="image" src="https://github.com/Liang-ZX/adaptdiffuser/assets/42173433/257e753d-6d03-45f7-84f3-a33c6fa568b1">
